name: Update myGitStar Summaries

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests
          pip install openai

      - name: Summarize starred repos with DeepSeek
        env:
          STARRED_GITHUB_TOKEN: ${{ secrets.STARRED_GITHUB_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: python scripts/summarize_stars.py

      - name: Commit and push changes
        env:
          STARRED_GITHUB_TOKEN: ${{ secrets.STARRED_GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README-sum.md
          git commit -m "update AI summarized stars [bot]" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${STARRED_GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
